### ISSUE TITLE
Explaination of sharedFolder vs ClusterSharedFolder

### ISSUE THREAD

**Issue by ericclaeren** [HipexBV/DeployConfiguration#21]
Hi,

I'm not getting the shared vs clustershared folder and can't find any documentation on the difference.
It seems that ClusterSharedFolder just extends SharedFolder, but I'm not sure in any thing else happens in the docker container with this.

E.g. Magento template.

`
$this->setSharedFolders([
    new SharedFolder('var/log'),
    new SharedFolder('var/report'),
    new ClusterSharedFolder('var/session'),
    new ClusterSharedFolder('pub/media'),
]);
`

Our pub/media is already a symlink to a nfs mounted folder, does changing this from shared to cluster shared affect this?

Could you explain the differences between the two types during a deployment?

Thanks, Eric

**Comment by Fgruntjes** [comment]
Hi Eric,

Thank you for your question. You are absolutely right that this is currently unclear.

Shared folders are shared over multiple deploys (versions) of your application and are placed in the `application/shared` folder. 
Cluster shared folders are also shared over multiple deploys. On top of that they are also shared over multiple application servers (or cloud instances) using an NFS mount stored on the load balancer or dedicated application server if no load balancer is existing.

Keep in mind that sharing folders over multiple servers is slow so for example placing your log folders there would greatly reduce the performance of your application.

**Comment by ericclaeren** [comment]
Thanks @Fgruntjes 

Does the internals of ClusterSharedFolder do anything at this time? For instance we have a symlink for pub/media to a nfs mount. This folder was a SharedFolder in our config. Will anything break when changing this to ClusterSharedFolder?

Want to make sure changing this is merely semantical change or are there other internal things going on when defining this as shared or cluster?

**Comment by Fgruntjes** [comment]
@ericclaeren this is currently only used in combination with our hybrid-cloud feature.

It is only use for the cloud part, the deployment is not different for normal servers.

**Comment by ericclaeren** [comment]
Thanks @Fgruntjes !
