### ISSUE TITLE
[Request] Adding the possibility to deploy language per given theme

### ISSUE THREAD

**Issue by jellesiderius** [HipexBV/DeployConfiguration#8]
The given locales are deployed for all themes. It would be a good addition to have the possibility to deploy language per given theme.

The problem now is that Theme/Default has "nl_NL" and "en_US" and Theme/Default2 has "fr_FR" and "de_DE". It deploys nl_NL, en_US, fr_FR and de_DE for both themes.

**Comment by stijnbernards** [comment]
Hi Jelle,

This is already possible with the current Hipex DeployConfiguration.

I currently use the following code to deploy separate themes:

```
        $this->addBuildCommand(new Command\Build\Magento2\SetupStaticContentDeploy(
            ['nl_NL'],
            'all',
            [
                '--theme=Magento/backend',
                '--theme=Theme/Second'
            ]
        ));

        $this->addBuildCommand(new Command\Build\Magento2\SetupStaticContentDeploy(
            ['de_AT'],
            'all',
            [
                '--theme=Magento/backend',
                '--theme=Theme/Third'
            ]
        ));
```

Let me know if this works for you.

**Comment by jellesiderius** [comment]
Thanks!
